package bsuir.ris.lab1.additions.entities;

public class DatabaseComponentName {

    public static final String UserTable = "users",
                               RoleTable = "roles",
                               BikeTable = "bikes",
                               FreeBikeTable = "free_bikes",
                               RentedBikeTable = "rented_bikes",
                               BikeWithConditionTable = "bike_with_conditions",
                               BikeMaterialTable = "materials",
                               BikeSpeedTable = "speeds",
                               DelayTimeTable = "delayTimes",
                               LateFeeTable = "late_fees",
                               RentalPriceTable = "rental_prices",
                               RentalTimeTable = "rental_times",
                               RentalHistoryTable = "rental_history",
                               RentTable = "rents",
                               ConditionTable = "conditions",
                               RentId = "rent_id",
                               BikeId = "bike_id",
                               RentalHistoryId = "history_id",
                               FreeBikeId = "freeBike_id",
                               RentedBikeId = "rentedBike_id",
                               UserId = "user_id",
                               RoleId = "role_id",
                               LateFeeId = "lateFee_id",
                               RentalPriceId = "rentalPrice_id",
                               RentalTimeId = "rentalTime_id",
                               BikeWithConditionId = "bike_with_condition_id",
                               BikeMaterialId = "material_id",
                               BikeSpeedId = "speed_id",
                               DelayTimeId = "delayTime_id",
                               ConditionId = "condition_id",
                               Time = "time",
                               Name = "name",
                               Model = "model",
                               Login = "login",
                               Password = "password",
                               Price = "price",
                               SpeedsCount = "count_of_speeds",
                               Email = "email",
                               Phone = "phoneNumber",
                               PassportData = "passportData",
                               Count = "count",
                               CreationYear = "year_of_creation",
                               Date = "date",
                               FinalAmount = "finalAmount";


}
